all:
	javac cap3/autoreferencia/*.java cap7/listaadj/arranjo/*.java cap7/listaadj/autoreferencia/*.java cap7/matrizadj/*.java cap7/*.java
clean:
	rm cap3/autoreferencia/*.class cap7/listaadj/arranjo/*.class cap7/listaadj/autoreferencia/*.class cap7/matrizadj/*.class cap7/*.class
